### ISSUE TITLE
using cross affects ci workflow

### ISSUE THREAD

**Issue by uncomfyhalomacro** [JuliaLang/juliaup#614]
I just found out that `juliaup` uses `action-rs/cargo` with `cross` set to true which limits installing additional dependencies. These dependencies might be needed for some crates e.g. reqwest with native-tls enabled looks for openssl-dev. The `cross` tool *can actually allow us to make a pre-build hook e.g. install libssl-dev or pkg-config inside the container before running cargo*. See https://github.com/cross-rs/cross/pull/678. However `action-rs/cargo` seems to not have updated to include the **pre-build** hook. This makes sense since the functionality was added since 2022 while `action-rs/cargo` has not been updated since 2021

Assuming we have the prebuild hook option, we can do the following to install openssl devel inside the `cross` container:

```yaml
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        pre-build: 'apt-get install -y libssl-dev pkg-config'
        command: check
        args: --target ${{matrix.target}} --features ${{matrix.features}}
```

There is an open issue at https://github.com/actions-rs/cargo/issues/115 but it's been two years since `action-rs/cargo` was updated.

This issue affects my PR #613 where I cannot test if my changes build correctly
