### ISSUE TITLE
Crash report (unwrap error on timeout?)

### ISSUE THREAD

**Issue by evetion** [JuliaLang/juliaup#986]
```toml
"name" = "Juliaup"
"operating_system" = "Mac OS 14.5.0 [64-bit]"
"crate_version" = "1.14.9"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 1348
"""
"cause" = 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("julialangnightlies-s3.julialang.org")), port: None, path: "/bin/macos/aarch64/julia-latest-macos-aarch64.tar.gz", query: None, fragment: None }, source: TimedOut }'
"method" = "Panic"
"backtrace" = """

   0: 0x1002b02b8 - core::result::unwrap_failed::h8e3b933261dd7fec
   1: 0x10014f010 - <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next::h8d4511c058de2f62
   2: 0x1001200a4 - juliaup::operations::update_version_db::h63cb733fe20d6355
   3: 0x100048c20 - juliaup::main::h4a3a519be046280b
   4: 0x100041384 - std::sys_common::backtrace::__rust_begin_short_backtrace::h24c3b07ba8d4c20a
   5: 0x1000521ac - _main"""
```

**Comment by tecosaur** [comment]
I've also hit this on Linux:

```toml
"name" = "Juliaup"
"operating_system" = "openSUSE 20240726.0.0 [64-bit]"
"crate_version" = "1.14.9"
"explanation" = """
Panic occurred in file 'src/operations.rs' at line 1348
"""
"cause" = 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("julialangnightlies-s3.julialang.org")), port: None, path: "/bin/linux/x86_64/julia-latest-linux-x86_64.tar.gz", query: None, fragment: None }, source: TimedOut }'
"method" = "Panic"
"backtrace" = """

   0: 0x7ff2a3da068b - <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next::h355999a7edec72ff
   1: 0x7ff2a3d6a01b - juliaup::operations::update_version_db::h25bb062aaefef9d4
   2: 0x7ff2a3c5f7e5 - juliaup::main::h610ad103c79ee503
   3: 0x7ff2a3c55963 - std::sys_common::backtrace::__rust_begin_short_backtrace::h25933f863152f4f8
   4: 0x7ff2a3c6c149 - main"""
```
